name: wherebus_app
description: "A new Flutter project."
publish_to: 'none' # Set to 'none' to prevent publishing to pub.dev

# Application version
version: 1.0.0+1

# Flutter SDK environment version
environment:
  sdk: ^3.5.2

# Dependencies required for your app
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  geolocator: ^9.0.0
  stroke_text: any
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.1

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/logo.png'

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific settings
flutter:
  uses-material-design: true

  # Assets for the application
  assets:
    - assets/admin.png
    - assets/user_avatar.png
    - assets/register_icon.png
    - assets/bus_avatar.png
    - assets/register-svgrepo-com.svg
    - assets/users.png
    - driver_avatar.png
    - users_no_border.png